# Generated by Django 3.0.6 on 2020-05-10 01:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200510_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
