# Generated by Django 3.0.6 on 2020-05-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200510_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resumo',
        ),
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Informativo', 'Informativo'), ('Erótico', 'Erótico'), ('Contos', 'Contos'), ('Romance', 'Romance')], max_length=30, null=True),
        ),
    ]
